### ISSUE TITLE
[object Object] error on thumbnail 

### ISSUE THREAD

**Issue by petenice** [click-rain/videolink#16]
{my_field_name:thumbnail} returning [object Object] error

**Comment by bryanburgers** [comment]
@petenice Thanks for reporting this issue. Would you mind answering a few questions so I can get to the bottom of this?

* What version of videolink are you using?
* Are you trying to embed a YouTube video or a Vimeo video?
* What browser were you using to access the control panel when you embedded the video?
* Does that tag return "[object Object]" or "[object Object] error"?
* Does this occur when you resave an existing entry? Or does it occur when you create a new entry?

**Comment by petenice** [comment]
Sorry about the delay. Answers follow:

1.  VideoLink 1.5.0
2. Trying to embed YouTube video
3. Browsering with Chrome 43
4. I believe it returned "[object Object]"
5. Error occured when creating a new entry

Thank you for your excellent work and helpful contribution! It's a great tool.

**Comment by peteheaney** [comment]
I was going to create a new issue, but I think this is probably the same thing....

The JSON feed returned by the YouTube API has changed.  You need to update videolink.js.  Change line 34 from:

`'thumbnail': data.items[0].snippet.thumbnails.maxres`

to:

`'thumbnail': data.items[0].snippet.thumbnails.high.url`

**Comment by bryanburgers** [comment]
@peteheaney Thanks for finding that! Would you be willing to submit a pull request?

**Comment by bryanburgers** [comment]
@petenice I believe this is fixed because of Pull Request #18. I've merged that into master. Can you give that a try to see if it fixes your problem before I cut a release?

**Comment by petenice** [comment]
Success! Thank you both!
