### ISSUE TITLE
Youtube api changed, extension stopped working

### ISSUE THREAD

**Issue by Yatish0833** [click-rain/videolink#19]
https://gdata.youtube.com/feeds/api/videos/xAHjjKf7A1Y?v=2&alt=jsonc

{"apiVersion":"2.1","error":{"code":410,"message":"No longer available","errors":[{"domain":"GData","code":"NoLongerAvailableException","internalReason":"No longer available"}]}}

**Comment by bryanburgers** [comment]
All references to gdata.youtube.com were removed in c1340b7 and released in version 1.5.0. Either you're using an old version of the add-on, you didn't update the themes folder when you updated the add-on, or you're somehow getting a cached version of the javascript.
